server:
  port: 6000



eureka:
  client:
    service-url:
      defzultZone: http://localhost:6000/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false

spring:
  application:
    name: cloud-center
